INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('San Francisco', 'CA', 'US');
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('Chennai', 'TA', 'India');
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('Madurai', 'TA', 'India');
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('Bengalore', 'KA', 'India');
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('Theni', 'TN', 'India');
INSERT INTO CITY (NAME, STATE, COUNTRY) VALUES ('Toronto', 'ON', 'Canada');

